### Apartment Price Predictor
### Author: Matti Pekari
### Description: This Shiny application predicts the price  
### of an apartment with inputted attributes.

library(shiny)

shinyUI(
    pageWithSidebar(
        headerPanel("Apartment Price Predictor"),
        sidebarPanel(
            sliderInput('zip', 'ZIP code', value = 100, min = 100, max = 990, step = 10),
            sliderInput('m2', 'Size (sq. meters)', value = 60, min = 20, max = 150, step = 1),
            sliderInput('year', 'Year Built', value = 1990, min = 1890, max = 2015, step = 1),
            sliderInput('floor', 'Floor', value = 5, min = 1, max = 10, step = 1),
            sliderInput('elevator', 'Elevator', value = 1, min = 0, max = 1, step = 1),
            sliderInput('condition', 'Condition', value = 1, min = 0, max = 2, step = 1)
        ),

        mainPanel(
            h3('Predicted Price (EUR)'),
            verbatimTextOutput("prediction"),
            br(),
            div("Welcome to Apartment Price Predictor!"),
            br(),
            div("This application predicts the price of an apartment with 
                inputted attributes. 
                You can set the attributes using the sliders on the left.
                The predicted price is shown in the field above."),
            br(),
            div("The prediction is generated by a predictive model 
                that was trained with actual apartment sales prices in Helsinki, Finland in 2013."),
            br(),
            div("Explanation of the attributes:"),
            HTML(
                "<ul>
                    <li>ZIP code: Postal code of the apartment</li>
                    <li>Size: Size of the apartment in square meters</li>
                    <li>Year built: Year when the the apartment building was constructed</li>
                    <li>Floor: Floor of the apartment (1 = ground floor)</li>
                    <li>Elevator: Does the building have an elevator (0 = no, 1 = yes)</li>
                    <li>Condition: Condition of the apartment (0 = bad, 1 = fair, 2 = excellent)</li>
                 </ul>"
            )
        )
    )
)